// Code generated by MockGen. DO NOT EDIT.
// Source: application/contract/writer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/diegoclair/log-parser/application/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// StartWriting mocks base method.
func (m *MockWriter) StartWriting(ctx context.Context, data <-chan dto.Report) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartWriting", ctx, data)
}

// StartWriting indicates an expected call of StartWriting.
func (mr *MockWriterMockRecorder) StartWriting(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWriting", reflect.TypeOf((*MockWriter)(nil).StartWriting), ctx, data)
}
